apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-mongodb
  labels:
    app: price-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-mongodb
  template:
    metadata:
      labels:
        app: price-mongodb
    spec:
      containers:
        - name: price-mongodb
          image: mongo:6.0.4  # Latest stable MongoDB version
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: mongodb-storage
          emptyDir: {}  # Use PersistentVolumeClaim for production
---
apiVersion: v1
kind: Service
metadata:
  name: price-mongodb
spec:
  selector:
    app: price-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
