apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: price-mongodb
  labels:
    app: price-mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price-mongodb
  template:
    metadata:
      labels:
        app: price-mongodb
    spec:
      containers:
        - name: price-mongodb
          image: mongo:6.0.4  # Latest stable MongoDB version
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "1Gi"         # Guaranteed 1 GiB RAM
              cpu: "500m"           # Guaranteed 0.5 CPU core
            limits:
              memory: "2Gi"         # Can burst up to 2 GiB RAM before OOM
              cpu: "1"              # Can burst up to 1 CPU core
      volumes:
        - name: mongodb-storage
          emptyDir: {}  # Use PersistentVolumeClaim for production
  serviceName: price-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: price-mongodb
spec:
  selector:
    app: price-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
