server:
  port: 9000
  netty:
    connection-timeouts: 2s
    idle-timeouts: 25s
  shutdown: graceful
spring:
  application:
    name: gateway-service
  lifecycle:
    timeout-per-shutdown-phase: 25s

  cloud:
    gateway:
      routes:
        - id: price-route
          uri: ${PRICE_SERVICE_URL:http://localhost:9002}
          predicates:
            # Match exactly the public API path your service expects:
            - Path=/api/public/v1/prices/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      uri: "http_server_requests"
    endpoint:
      gateway:
        enabled: true
      metrics:
        enabled: true
      prometheus:
        enabled: true
      health:
        show-details: always
    distribution:
      percentiles-histogram: # enable histogram for percentile
        http.server.requests: true
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 500ms, 1s


# Security
logging:
  level:
    root: INFO
    io.example.springcloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{trace_id:-N/A}] [%X{span_id:-N/A}] %-5level %logger{36} - %msg%n"
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: price-route
          uri: ${PRICE_SERVICE_URL:http://localhost:9002}
          predicates:
            # Match exactly the public API path your service expects:
            - Path=/api/public/v1/prices/**
