services:
  mongodb:
    image: mongo:6.0.4
    container_name: "mongodb"
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongostat -n 1"
    networks:
      - shared-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
volumes:
  prometheus-data:
  grafana-data:
  loki-data: