apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
  labels:
    app: price-service
spec:
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      containers:
        - name: price-service
          image: price-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://price-mongodb:27017/price-db

          resources:
            requests:
              cpu: "450m"
              memory: "712Mi"
            limits:
              cpu: "550m"
              memory: "912Mi"
