apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-service
  labels:
    app: price-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
    spec:
      containers:
        - name: price-service
          image: price-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://price-mongodb:27017/price-db